class UserInterests {
  static const List<String> interests = [
    'Sports',
    'Music',
    'Art',
    'Gaming',
    'Reading',
    'Science',
    'Technology',
    'Photography',
    'Fashion',
    'Cooking',
    'Dancing',
    'Movies',
    'Travel',
    'Fitness',
    'Writing',
    'Anime/Manga',
    'Theater',
    'Environment',
    'Politics',
    'Volunteering',
    'Other',
  ];

  static const List<String> schoolYears = [
    '9',
    '10',
    '11',
    '12',
    '13',
    'University',
    'Graduate',
  ];

  static const List<String> clubs = [
    'Student Council',
    'Drama Club',
    'Music Club',
    'Art Club',
    'Science Club',
    'Math Club',
    'Sports Team',
    'Debate Club',
    'Environmental Club',
    'Robotics Club',
    'Chess Club',
    'Photography Club',
    'Yearbook',
    'Newspaper',
    'Coding Club',
    'Dance Team',
    'Choir',
    'Band',
    'Orchestra',
    'Volunteer Organization',
    'Other',
  ];
}
